CREATE TABLE `project.datastore.table` (
  region_tags ARRAY<STRING> OPTIONS(description="List of tags associated with the region. (Must exist and not be empty for record to be ingested)"),
  evaluation_date TIMESTAMP OPTIONS(description="Date and time of the evaluation."),
  product_area STRING OPTIONS(description="Derived from the github_link (e.g., 'bigquery' from the sample URL)."),
  git_info_raw_json STRING OPTIONS(description="Entire original 'git_info' object as a JSON string."),
  evaluation_data_raw_json STRING OPTIONS(description="Entire original 'evaluation_data' object as a JSON string."),
  overall_compliance_score INTEGER OPTIONS(description="Overall compliance score from 'evaluation_data'."),
  identified_generic_problem_categories ARRAY<STRING> OPTIONS(description="List of generic problem categories from 'evaluation_data'."),
  runnability_score INTEGER OPTIONS(description="Score for 'Runnability & Configuration' criterion."),
  runnability_assessment STRING OPTIONS(description="Assessment for 'Runnability & Configuration' criterion."),
  api_effectiveness_score INTEGER OPTIONS(description="Score for 'API Effectiveness (googleapis/googleapis)' criterion."),
  api_effectiveness_assessment STRING OPTIONS(description="Assessment for 'API Effectiveness (googleapis/googleapis)' criterion."),
  code_clarity_score INTEGER OPTIONS(description="Score for 'Comments & Code Clarity' criterion."),
  code_clarity_assessment STRING OPTIONS(description="Assessment for 'Comments & Code Clarity' criterion."),
  consistency_score INTEGER OPTIONS(description="Score for 'Formatting & Consistency' criterion."),
  consistency_assessment STRING OPTIONS(description="Assessment for 'Formatting & Consistency' criterion."),
  language_score INTEGER OPTIONS(description="Score for 'Language Best Practices' criterion."),
  language_assessment STRING OPTIONS(description="Assessment for 'Language Best Practices' criterion."),
  github_link STRING OPTIONS(description="Direct link to file in GitHub")
)